### PR TITLE
Add PageEnd(first page/last page with pageOrder) to Toolbar

### LINKED ISSUE #41: Big Sur and Apple Silicon Status
TLDR: The App Store version of **SimpleComic won't work in Big Sur on launch day** (today) but should be updated for compatibility soon. Apple Silicon support TBD but expected not to be a problem.

---------

I've been in a multi-step move over the past few months, so haven't had time for side projects but that's closing up now.

For the Mac App store version, I'll look into putting together the newest builds that support Big Sur and Apple Silicon soon.

Looks like Big Sur status was fixed up here: https://github.com/MaddTheSane/Simple-Comic/issues/37

Not sure about Apple Silicon, hopefully it's an easy cross-compile target. I'm getting one of the new MacBooks next week and will test it out then.

### PR DESCRIPTION
**Pull request by touta**
Add PageEndToolbarItem to Toolbar (not default item), which call firstPage: or lastPage: accourding to pageOrder.

It may not good to use NSTouchBarSkipToStartTemplate/NSTouchBarSkipToEndTemplate, and should create new image like "|<" and ">|".
But sorry I'm not good at vectorized images.

### CODE REVIEW

**Comment by nickv2002** [comment]
Thanks for the submission @touta sorry I missed this earlier (May was… well you probably are aware of the state of things ☹️).

For vector images have you considered [SFSymbols](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/)?

Anyway, I'll try out your feature next time I play around with the code.

**Comment by touta** [comment]
@nickv2002
Thank you for reply.

Yep, I did check SFSymbols, but I could't found suitable icon.
Even 'forward.end' of SFSymbols looks same to NSTouchBarSkipToStartTemplate, it also lacks coherence to turn-page button which near-by. 
(and I don't know how to set it to label on storybord without rasterizing as image. So I used image named NSTouchbar* )

It functionally works and I don't mind lacking of coherence as for using myself, but not everybody may don't.

I'm newbie for this kind of pull-reqest. I'm sorry if I'm rude.
Let me know if you have any questions.

**Comment by nickv2002** [comment]
Your PR is not rude, it's appreciated!
I'm busy but will take a look next time I have a chance.
Thanks

**Comment by nickv2002** [comment]
Also adding Page Start/End buttons from https://github.com/MaddTheSane/Simple-Comic/pull/25 to this App Store build (merged here https://github.com/MaddTheSane/Simple-Comic/commit/34fd6da8a9e273f97545c69f07fcc4d8eb795935 )

**Comment by nickv2002** [comment]
@MaddTheSane note that the app store only accepts 64-bit ARM/x86 builds so I had to change some of the build settings on the `WebPMac` target to remove other architecture refs. It seems these are ignored by Git but I figured worth documenting here for my future ref. Also something that might be changed upstream?
ARM and x86_64 settngs needed for App Store

**Pull request merged**
