### PR TITLE
Contextual menu item: Look Up (Dictionary panel)

### PR DESCRIPTION
**Pull request by DavidPhillipOster**
Add support for the standard dictionary panel to OCR'ed text.

Documented, with screen shots, in https://davidphilliposter.dreamwidth.org/3454.html

### CODE REVIEW

**Review by nickv2002 — APPROVED** [review]

**Comment by nickv2002** [comment]
LGTM. Can integrate it into the next build we push out for the store/signed release. 👍

**Comment by DavidPhillipOster** [comment]
Thank you both. I'm truly pleased that you acted on this so quickly. I'm happy to wait for the next push to the store/signed release.

**Comment by DavidPhillipOster** [comment]
A "Search With Google" contextual menu command would look like:

    - (void)google:(id)sender {
      NSString *s = [[[self selection] componentsSeparatedByString:@"\n"] firstObject];
      NSURLComponents *parts = [[NSURLComponents alloc] initWithString:@"https://www.google.com/search"];
      parts.queryItems = @[ [[NSURLQueryItem alloc] initWithName:@"q" value:s] ];
      NSURL *url = [parts URL];
      [NSWorkspace.sharedWorkspace openURL:url];
    }

but I don't think it is a good fit for Simple Comic so I didn't include it in the pull request.

**Comment by nickv2002** [comment]
Now in TestFlight if you want to try see: https://github.com/MaddTheSane/Simple-Comic/releases/tag/App-Store-1.9.6

Update: [the same build has been released to as a regular release now too](https://apps.apple.com/us/app/simple-comic/id1497435571?mt=12)

**Pull request merged**
