### PR TITLE
Fix: Frequent software freeze since 1.9.3 update

### LINKED ISSUE #74: Frequent software freeze since 1.9.3 update
Since 1.9.3 update (on macOS 11.6.6), I am experiencing the software quickly slowing down until it becomes unresponsive with rotating wheel. Upon opening a 100MB file, the memory usage quickly rise from few hundred megabytes to multiple gigabytes, which may be the reason of slowdown. At this point, the only way to close the app is to force quit.

### PR DESCRIPTION
**Pull request by DavidPhillipOster**
Pull request of OCRTracker.m, & OCRTracker.{h,m} that cancels OCR requests once their result is no longer needed. This fixes [Frequent software freeze since 1.9.3 update #74](https://github.com/MaddTheSane/Simple-Comic/issues/74)
Tested with the Japanese document from @[Patalliro8](https://github.com/Patalliro8) - Before, after using next/previous to go all the way through the document and back a total of 4 times, I'd see the symptoms. After, RAM usage stays low, and responsiveness is still good.

### CODE REVIEW

**Review by nickv2002 — APPROVED** [review]

**Comment by nickv2002** [comment]
Thanks! If this looks good to @MaddTheSane also we can merge and send to Apple.

**Comment by nickv2002** [comment]
Great, I've built this and sent to build over to Apple for a new release ([version 1.9.4](https://github.com/MaddTheSane/Simple-Comic/releases/tag/App-Store-1.9.4))

**Comment by Patalliro8** [comment]
Thank you very much for the fix!!
Is there any chance we may have an ability to turn off the Live Text feature entirely in the future?
I still seem to encounter the large memory usage and eventual freeze with version 1.9.4 (290).

**Comment by DavidPhillipOster** [comment]
@Patalliro8 your bug reports have helped me get the bugs out of that feature - problems I'm not seeing. So if you have steps to reproduce, please file them as [issues](https://github.com/MaddTheSane/Simple-Comic/issues).
Before June 24 I will submit a pull request that adds a checkbox to preferences to turn the feature off.  (You'd think that just adding a checkbox would be simple, but I have to cope with localization issues, with the user changing the state of that checkbox while in the middle of reading a book, and that feature powers future features I'm working on:  a Find command, and Spotlight indexing.)

**Comment by DavidPhillipOster** [comment]
https://github.com/MaddTheSane/Simple-Comic/pull/79 is a start. It will let you turn off the feature from Terminal even before there is a checkbox in the U.I.

**Pull request merged**
