### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by J-rg**
- Removes the “Auto-save open windows” option in favor of respecting the “Close windows when quitting an app” setting in System Preferences.
- Replaces NSImage.imageFileTypes(), which was deprecated in Yosemite.
- Adds file extensions to allowedFileTypes as UTIs can be unreliable.
- Fixes blurry text in the “Click to select page” labels. (The “Drag to crop” text is clipped since #​22 btw.)
- Adds a build flag for compiling QuickComic with private API.
- Moves the “Turn Page” toolbar items before the window title.

### CODE REVIEW

**Comment by nickv2002** [comment]
Good time to update the Mac App Store version or should we wait for the next Monterey release?

**Comment by MaddTheSane** [comment]
We probably do need a new release.
I don't if we should wait for Monterey or release now.

**Comment by nickv2002** [comment]
OK, let's wait for Monterey. I'll plan to do one shortly after that is released.

**Comment by nickv2002** [comment]
If you have Monterey you can join the [TestFlight beta of the new App store build here](https://testflight.apple.com/join/oHcg1JAt). Please give it a shot and LMK if there are any issues. If things look good I'll release this as 1.9.2. Build is based on https://github.com/MaddTheSane/Simple-Comic/commit/bf801a7071c33b902fbb6ef77a93be1f8358d19b

**Pull request merged**
