### PR TITLE
Fix: iBeam cursor when mouse is over recognized text not initially showing.

### PR DESCRIPTION
**Pull request by DavidPhillipOster**
This is a change to one file: OCRTracker.m OCRTracker uses the selection layer to compute the the cursor rects for the i-beam cursor. Simple Comic creates those selection layers during its `drawRect:` This change delays the call to `invalidateCursorRectsForView:` late enough that `didResetCursorRects` has the data that it needs to do the reset.

### CODE REVIEW

**Review by DavidPhillipOster — COMMENTED** [review]
Aargh! This is isn't what I meant. I just meant:

https://github.com/MaddTheSane/Simple-Comic/pull/72/commits/e5645a417ae8c5ea5f96f62bbc7d46b46f577704


Just the one file, Not the stack of seven commits!

**Comment by nickv2002** [comment]
Oops @DavidPhillipOster - I already sent the previous code [though App review](https://github.com/MaddTheSane/Simple-Comic/releases/tag/App-Store-1.9.3). Is this an important fix or should I wait for you to tweak some other stuff?

In any case thanks for your help!

**Comment by DavidPhillipOster** [comment]
Sigh - It is both harmless and important. I've rewritten the OCR code about
six times, most of them in a simplified mock up. Without this last change
the mouse cursor won't automatically change to an i-beam unless you click
and slightly drag. (it's fine from then on as long as you stay on the page)

With this 3 line change, even if you take no further action, the mouse
cursor will change to an i-beam when it moves over selectable text.

----
I'm going to delete my fork of Simple-Comic, and re-create it as a fresh
fork of yours, and ONLY put well-test changes that you can pull in that.
Thank you for your patience with me.

**Comment by MaddTheSane** [comment]
I've cherry-picked the commits.

**Comment by DavidPhillipOster** [comment]
Thanks! I'm still learning commit tree management in git and github.

I've got Find starting to work: The standard Find submenu works. Apple's Find UI shows in the document windows, and it is starting to work, so far, for search forward, but only within the current page. I still must write the obvious missing pieces: search previous, searches that extend beyond the current page. Also, the selection is subtle, so I'll need to animate the selection change, like Safari does.

**Comment by DavidPhillipOster** [comment]
I've written up more of a description of my changes on my personal blog:
https://davidphilliposter.dreamwidth.org/1745.html

**Pull request closed without merging**
